# Generated by Django 6.0.1 on 2026-01-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_cart_unique_together_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-added_at']},
        ),
    ]
