# Generated by Django 6.0.1 on 2026-02-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
