# Generated by Django 6.0.1 on 2026-02-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_profile_is_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
